export const constants = {
    GET_DESTINATIONS: 'GET_DESTINATIONS',
    GET_TRIP_DESTINATIONS: 'GET_TRIP_DESTINATIONS',
    ADD_TRIP_DESTINATION: 'ADD_TRIP_DESTINATION',
    GET_TRIP_TOTAL: 'GET_TRIP_TOTAL',
    REMOVE_TRIP_DESTINATION: 'REMOVE_TRIP_DESTINATION'
}